export const currency = '₹';

export const allCountries = [
    {
        name: "United Arab Emirates",
        code: "+971",
        icon: "AE",
        curr: "AED",
    },
    { name: "Saudi Arabia", code: "+966", icon: "SA", curr: "SAR" },
    { name: "Qatar", code: "+974", icon: "QA", curr: "QAR" },
    { name: "Oman", code: "+968", icon: "OM", curr: "OMR" },
    { name: "Bahrain", code: "+973", icon: "BH", curr: "BHD" },
    { name: "Kuwait", code: "+965", icon: "KW", curr: "KWD" },
    { name: "India", code: "+91", icon: "IN", curr: "INR" },
    { name: "United Kingdom", code: "+44", icon: "GB", curr: "GBP" },
    { name: "United States", code: "+1", icon: "US", curr: "USD" },
    { name: "Bhutan", code: "+975", icon: "BT", curr: "BTN" },
    { name: "Afghanistan", code: "+93", icon: "AF", curr: "AFN" },
    { name: "Argentina", code: "+54", icon: "AR", curr: "ARS" },
    { name: "Australia", code: "+61", icon: "AU", curr: "AUD" },
    { name: "Bangladesh", code: "+880", icon: "BD", curr: "BDT" },
    { name: "Belgium", code: "+32", icon: "BE", curr: "EUR" },
    { name: "Brazil", code: "+55", icon: "BR", curr: "BRL" },
    { name: "CANADA", code: "+1", icon: "CA", curr: "CAD" },
    { name: "China", code: "+86", icon: "CN", curr: "CNY" },
    { name: "Colombia", code: "+57", icon: "CO", curr: "COP" },
    { name: "Dominica", code: "+1767", icon: "DM", curr: "XCD" },
    { name: "Chile", code: "+56", icon: "CL", curr: "CLP" },
    { name: "Denmark", code: "+45", icon: "DK", curr: "DKK" },
    { name: "Egypt", code: "+20", icon: "EG", curr: "EGP" },
    { name: "Finland", code: "+358", icon: "FI", curr: "EUR" },
    { name: "France", code: "+33", icon: "FR", curr: "EUR" },
    { name: "Germany", code: "+49", icon: "DE", curr: "EUR" },
    { name: "Hong Kong", code: "+852", icon: "HK", curr: "HKD" },
    { name: "Indonesia", code: "+62", icon: "ID", curr: "IDR" },
    { name: "Iraq", code: "+964", icon: "IQ", curr: "IQD" },
    { name: "Italy", code: "+39", icon: "IT", curr: "EUR" },
    { name: "Belgium", code: "+32", icon: "BE", curr: "EUR" },
    { name: "Japan", code: "+81", icon: "JP", curr: "JPY" },
    { name: "Jamica", code: "+1876", icon: "JM", curr: "JMD" },
    { name: "Kenya", code: "+254", icon: "KE", curr: "KES" },
    { name: "Malaysia", code: "+960", icon: "MY", curr: "MYR" },
    { name: "Maldives", code: "+960", icon: "MV", curr: "MVR" },
    { name: "Mauritius", code: "+230", icon: "MU", curr: "MUR" },
    { name: "Myanmar", code: "+95", icon: "MM", curr: "MMK" },
    { name: "New Zealand", code: "+64", icon: "NZ", curr: "NZD" },
    { name: "Nepal", code: "+977", icon: "NP", curr: "NPR" },
    { name: "Netherlands", code: "+31", icon: "NL", curr: "EUR" },
    { name: "Nigeria", code: "+234", icon: "NG", curr: "NGN" },
    { name: "Norway", code: "+47", icon: "NO", curr: "NOR" },
    { name: "Pakistan", code: "+92", icon: "PK", curr: "PKR" },
    { name: "Poland", code: "+48", icon: "PL", curr: "PLN" },
    { name: "Portugal", code: "+351", icon: "PT", curr: "EUR" },
    { name: "Russia", code: "+7", icon: "RU", curr: "RUB" },
    { name: "Singapore", code: "+65", icon: "SG", curr: "BND" },
    { name: "Souht Africa", code: "+27", icon: "ZA", curr: "ZAR" },
    { name: "Spain", code: "+34", icon: "ES", curr: "EUR" },
    { name: "Sri Lanka", code: "+94", icon: "LK", curr: "LKR" },
    { name: "Switzerland", code: "+41", icon: "CH", curr: "CHF" },
    { name: "Taiwan", code: "+886", icon: "TW", curr: "TWD" },
    { name: "Thailand", code: "+66", icon: "TH", curr: "THB" },
    { name: "Turkey", code: "+90", icon: "TR", curr: "TRY" },
    { name: "Ukraine", code: "+380", icon: "UA", curr: "UAH" },
    { name: "Vietnam", code: "+84", icon: "VN", curr: "VND" },
];